//////////////////////////////////////////////
//   BE Trainer.NET for Grand Theft Auto V
//             by BE.Tenner
//      Copyright (c) BE Group 2015
//               Thanks to
//    ScriptHookV & ScriptHookVDotNet
//  Native Trainer & Enhanced Native Trainer
//////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GTAVBETrainerDotNet.Model
{
    /// <summary>
    /// Player model storage
    /// </summary>
    public static class ModelStorage
    {
        /// <summary>
        /// Michael
        /// </summary>
        public static readonly ModelData MODEL_MICHAEL = new ModelData("Michael", "player_zero");

        /// <summary>
        /// Franklin
        /// </summary>
        public static readonly ModelData MODEL_FRANKLIN = new ModelData("Franklin", "player_one");

        /// <summary>
        /// Trevor
        /// </summary>
        public static readonly ModelData MODEL_TREVOR = new ModelData("Trevor", "player_two");

        /// <summary>
        /// Animals
        /// </summary>
        public static readonly ModelData[] MODEL_ANIMALS = new ModelData[]
        {
            new ModelData("Boar", "a_c_boar"), new ModelData("Cat", "a_c_cat_01"), new ModelData("Chimp", "a_c_chimp"), new ModelData("Chop", "a_c_chop"), new ModelData("Cormorant", "a_c_cormorant"), 
            new ModelData("Cow", "a_c_cow"), new ModelData("Coyote", "a_c_coyote"), new ModelData("Crow", "a_c_crow"), new ModelData("Deer", "a_c_deer"), new ModelData("Dolphin", "a_c_dolphin"), 
            new ModelData("Fish", "a_c_fish"), new ModelData("German Shepherd", "a_c_shepherd"), new ModelData("Grey Whale", "a_c_whalegrey"), new ModelData("Hammerhead Shark", "a_c_sharkhammer"), 
            new ModelData("Hawk", "a_c_chickenhawk"), new ModelData("Hen", "a_c_hen"), new ModelData("Humpback", "a_c_humpback"), new ModelData("Husky", "a_c_husky"), 
            new ModelData("Killer Whale", "a_c_killerwhale"), new ModelData("Mountain Lion", "a_c_mtlion"), new ModelData("Pig", "a_c_pig"), new ModelData("Pigeon", "a_c_pigeon"), 
            new ModelData("Poodle", "a_c_poodle"), new ModelData("Pug", "a_c_pug"), new ModelData("Rabbit", "a_c_rabbit_01"), new ModelData("Rat", "a_c_rat"), new ModelData("Retriever", "a_c_retriever"), 
            new ModelData("Rhesus", "a_c_rhesus"), new ModelData("Rottweiler", "a_c_rottweiler"), new ModelData("Seagull", "a_c_seagull"), new ModelData("Stingray", "a_c_stingray"), 
            new ModelData("Tiger Shark", "a_c_sharktiger"), new ModelData("Westy", "a_c_westy"), 
        };

        public static readonly ModelData[] MODEL_NPCS = new ModelData[]
        {
            new ModelData("Abigail Mathers (CS)", "csb_abigail"), new ModelData("Abigail Mathers (IG)", "ig_abigail"), new ModelData("Abner", "u_m_y_abner"), 
            new ModelData("African American Male", "a_m_m_afriamer_01"), new ModelData("Agent (CS)", "csb_agent"), new ModelData("Agent (IG)", "ig_agent"), new ModelData("Agent 14 (CS)", "csb_mp_agent14"), 
            new ModelData("Agent 14 (IG)", "ig_mp_agent14"), new ModelData("Air Hostess", "s_f_y_airhostess_01"), new ModelData("Air Worker Male", "s_m_y_airworker"), 
            new ModelData("Al Di Napoli Male", "u_m_m_aldinapoli"), new ModelData("Alien", "s_m_m_movalien_01"), new ModelData("Altruist Cult Mid-Age Male", "a_m_m_acult_01"), 
            new ModelData("Altruist Cult Old Male", "a_m_o_acult_01"), new ModelData("Altruist Cult Old Male 2", "a_m_o_acult_02"), new ModelData("Altruist Cult Young Male", "a_m_y_acult_01"), 
            new ModelData("Altruist Cult Young Male 2", "a_m_y_acult_02"), new ModelData("Amanda De Santa (CS)", "cs_amandatownley"), new ModelData("Amanda De Santa (IG)", "ig_amandatownley"), 
            new ModelData("Ammu-Nation City Clerk", "s_m_y_ammucity_01"), new ModelData("Ammu-Nation Rural Clerk", "s_m_m_ammucountry"), new ModelData("Andreas Sanchez (CS)", "cs_andreas"), 
            new ModelData("Andreas Sanchez (IG)", "ig_andreas"), new ModelData("Anita Mendoza", "csb_anita"), new ModelData("Anton Beaudelaire", "csb_anton"), 
            new ModelData("Anton Beaudelaire", "u_m_y_antonb"), new ModelData("Armenian Boss", "g_m_m_armboss_01"), new ModelData("Armenian Goon", "g_m_m_armgoon_01"), 
            new ModelData("Armenian Goon 2", "g_m_y_armgoon_02"), new ModelData("Armenian Lieutenant", "g_m_m_armlieut_01"), new ModelData("Armoured Van Security", "mp_s_m_armoured_01"), 
            new ModelData("Armoured Van Security", "s_m_m_armoured_01"), new ModelData("Armoured Van Security 2", "s_m_m_armoured_02"), new ModelData("Army Mechanic", "s_m_y_armymech_01"), 
            new ModelData("Ashley Butler (CS)", "cs_ashley"), new ModelData("Ashley Butler (IG)", "ig_ashley"), new ModelData("Autopsy Tech", "s_m_y_autopsy_01"), 
            new ModelData("Autoshop Worker", "s_m_m_autoshop_01"), new ModelData("Autoshop Worker 2", "s_m_m_autoshop_02"), new ModelData("Azteca", "g_m_y_azteca_01"), 
            new ModelData("Baby D", "u_m_y_babyd"), new ModelData("Ballas East Male", "g_m_y_ballaeast_01"), new ModelData("Ballas Female", "g_f_y_ballas_01"), 
            new ModelData("Ballas OG", "csb_ballasog"), new ModelData("Ballas OG (IG)", "ig_ballasog"), new ModelData("Ballas Original Male (IG)", "g_m_y_ballaorig_01"), 
            new ModelData("Ballas South Male", "g_m_y_ballasout_01"), new ModelData("Bank Manager (CS)", "cs_bankman"), new ModelData("Bank Manager (IG)", "ig_bankman"), 
            new ModelData("Bank Manager Male", "u_m_m_bankman"), new ModelData("Barber Female", "s_f_m_fembarber"), new ModelData("Barman", "s_m_y_barman_01"), new ModelData("Barry (CS)", "cs_barry"), 
            new ModelData("Barry (IG)", "ig_barry"), new ModelData("Bartender", "s_f_y_bartender_01"), new ModelData("Bartender (Rural)", "s_m_m_cntrybar_01"), 
            new ModelData("Baywatch Female", "s_f_y_baywatch_01"), new ModelData("Baywatch Male", "s_m_y_baywatch_01"), new ModelData("Beach Female", "a_f_m_beach_01"), 
            new ModelData("Beach Male", "a_m_m_beach_01"), new ModelData("Beach Male 2", "a_m_m_beach_02"), new ModelData("Beach Muscle Male", "a_m_y_musclbeac_01"), 
            new ModelData("Beach Muscle Male 2", "a_m_y_musclbeac_02"), new ModelData("Beach Old Male", "a_m_o_beach_01"), new ModelData("Beach Tramp Female", "a_f_m_trampbeac_01"), 
            new ModelData("Beach Tramp Male", "a_m_m_trampbeac_01"), new ModelData("Beach Young Female", "a_f_y_beach_01"), new ModelData("Beach Young Male", "a_m_y_beach_01"), 
            new ModelData("Beach Young Male 2", "a_m_y_beach_02"), new ModelData("Beach Young Male 3", "a_m_y_beach_03"), new ModelData("Best Man (IG)", "ig_bestmen"), 
            new ModelData("Beverly Felton (CS)", "cs_beverly"), new ModelData("Beverly Felton (IG)", "ig_beverly"), new ModelData("Beverly Hills Female", "a_f_m_bevhills_01"), 
            new ModelData("Beverly Hills Female 2", "a_f_m_bevhills_02"), new ModelData("Beverly Hills Male", "a_m_m_bevhills_01"), new ModelData("Beverly Hills Male 2", "a_m_m_bevhills_02"), 
            new ModelData("Beverly Hills Young Female", "a_f_y_bevhills_01"), new ModelData("Beverly Hills Young Female 2", "a_f_y_bevhills_02"), 
            new ModelData("Beverly Hills Young Female 3", "a_f_y_bevhills_03"), new ModelData("Beverly Hills Young Female 4", "a_f_y_bevhills_04"), 
            new ModelData("Beverly Hills Young Male", "a_m_y_bevhills_01"), new ModelData("Beverly Hills Young Male 2", "a_m_y_bevhills_02"), new ModelData("Bigfoot (CS)", "cs_orleans"), 
            new ModelData("Bigfoot (IG)", "ig_orleans"), new ModelData("Bike Hire Guy", "u_m_m_bikehire_01"), new ModelData("Biker Chic Female", "u_f_y_bikerchic"), 
            new ModelData("Black Ops Soldier", "s_m_y_blackops_01"), new ModelData("Black Ops Soldier 2", "s_m_y_blackops_02"), new ModelData("Black Ops Soldier 3", "s_m_y_blackops_03"), 
            new ModelData("Black Street Male", "a_m_y_stbla_01"), new ModelData("Black Street Male 2", "a_m_y_stbla_02"), new ModelData("Bodybuilder Female", "a_f_m_bodybuild_01"), 
            new ModelData("Bouncer", "s_m_m_bouncer_01"), new ModelData("Brad (CS)", "cs_brad"), new ModelData("Brad (IG)", "ig_brad"), new ModelData("Brad's Cadaver (CS)", "cs_bradcadaver"), 
            new ModelData("Breakdancer Male", "a_m_y_breakdance_01"), new ModelData("Bride", "csb_bride"), new ModelData("Bride (IG)", "ig_bride"), new ModelData("Burger Drug Worker", "csb_burgerdrug"), 
            new ModelData("Burger Drug Worker", "u_m_y_burgerdrug_01"), new ModelData("Busboy", "s_m_y_busboy_01"), new ModelData("Business Casual", "a_m_y_busicas_01"), 
            new ModelData("Business Female 2", "a_f_m_business_02"), new ModelData("Business Male", "a_m_m_business_01"), new ModelData("Business Young Female", "a_f_y_business_01"), 
            new ModelData("Business Young Female 2", "a_f_y_business_02"), new ModelData("Business Young Female 3", "a_f_y_business_03"), new ModelData("Business Young Female 4", "a_f_y_business_04"), 
            new ModelData("Business Young Male", "a_m_y_business_01"), new ModelData("Business Young Male 2", "a_m_y_business_02"), new ModelData("Business Young Male 3", "a_m_y_business_03"), 
            new ModelData("Busker", "s_m_o_busker_01"), new ModelData("Car 3 Guy 1", "csb_car3guy1"), new ModelData("Car 3 Guy 1 (IG)", "ig_car3guy1"), new ModelData("Car 3 Guy 2", "csb_car3guy2"), 
            new ModelData("Car 3 Guy 2 (IG)", "ig_car3guy2"), new ModelData("Car Buyer (CS)", "cs_carbuyer"), new ModelData("Casey (CS)", "cs_casey"), new ModelData("Casey (IG)", "ig_casey"), 
            new ModelData("Chef", "s_m_y_chef_01"), new ModelData("Chef", "csb_chef"), new ModelData("Chef (CS)", "csb_chef2"), new ModelData("Chef (IG)", "ig_chef"), new ModelData("Chef (IG)", "ig_chef2"), 
            new ModelData("Chemical Plant Security", "s_m_m_chemsec_01"), new ModelData("Chemical Plant Worker", "g_m_m_chemwork_01"), new ModelData("Chinese Boss", "g_m_m_chiboss_01"), 
            new ModelData("Chinese Goon", "g_m_m_chigoon_01"), new ModelData("Chinese Goon", "csb_chin_goon"), new ModelData("Chinese Goon 2", "g_m_m_chigoon_02"), 
            new ModelData("Chinese Goon Older", "g_m_m_chicold_01"), new ModelData("Chip", "u_m_y_chip"), new ModelData("Claude Speed", "mp_m_claude_01"), 
            new ModelData("Clay Jackson (The Pain Giver) (IG)", "ig_claypain"), new ModelData("Clay Simons (The Lost) (CS)", "cs_clay"), new ModelData("Clay Simons (The Lost) (IG)", "ig_clay"),
            new ModelData("Cletus", "csb_cletus"), new ModelData("Cletus (IG)", "ig_cletus"), new ModelData("Clown", "s_m_y_clown_01"), new ModelData("Construction Worker", "s_m_y_construct_01"), 
            new ModelData("Construction Worker 2", "s_m_y_construct_02"), new ModelData("Cop", "csb_cop"), new ModelData("Cop Female", "s_f_y_cop_01"), new ModelData("Cop Male", "s_m_y_cop_01"), 
            new ModelData("Corpse Female", "u_f_m_corpse_01"), new ModelData("Corpse Young Female", "u_f_y_corpse_01"), new ModelData("Corpse Young Female 2", "u_f_y_corpse_02"), 
            new ModelData("Crew Member", "s_m_m_ccrew_01"), new ModelData("Cris Formage (CS)", "cs_chrisformage"), new ModelData("Cris Formage (IG)", "ig_chrisformage"), 
            new ModelData("Customer", "csb_customer"), new ModelData("Cyclist Male", "a_m_y_cyclist_01"), new ModelData("Cyclist Male", "u_m_y_cyclist_01"), new ModelData("Dale (CS)", "cs_dale"), 
            new ModelData("Dale (IG)", "ig_dale"), new ModelData("Dave Norton (CS)", "cs_davenorton"), new ModelData("Dave Norton (IG)", "ig_davenorton"), new ModelData("Dead Hooker", "mp_f_deadhooker"), 
            new ModelData("Dealer", "s_m_y_dealer_01"), new ModelData("Debra (CS)", "cs_debra"), new ModelData("Denise (CS)", "cs_denise"), new ModelData("Denise (IG)", "ig_denise"), 
            new ModelData("Denise's Friend", "csb_denise_friend"), new ModelData("Devin (CS)", "cs_devin"), new ModelData("Devin (IG)", "ig_devin"), new ModelData("Devin's Security", "s_m_y_devinsec_01"), 
            new ModelData("Dima Popov (CS)", "csb_popov"), new ModelData("Dima Popov (IG)", "ig_popov"), new ModelData("DOA Man", "u_m_m_doa_01"), new ModelData("Dock Worker", "s_m_m_dockwork_01"), 
            new ModelData("Dock Worker", "s_m_y_dockwork_01"), new ModelData("Doctor", "s_m_m_doctor_01"), new ModelData("Dom Beasley (CS)", "cs_dom"), new ModelData("Dom Beasley (IG)", "ig_dom"), 
            new ModelData("Doorman", "s_m_y_doorman_01"), new ModelData("Downhill Cyclist", "a_m_y_dhill_01"), new ModelData("Downtown Female", "a_f_m_downtown_01"), 
            new ModelData("Downtown Male", "a_m_y_downtown_01"), new ModelData("Dr. Friedlander (CS)", "cs_drfriedlander"), new ModelData("Dr. Friedlander (IG)", "ig_drfriedlander"), 
            new ModelData("Dressy Female", "a_f_y_scdressy_01"), new ModelData("DW Airport Worker", "s_m_y_dwservice_01"), new ModelData("DW Airport Worker 2", "s_m_y_dwservice_02"), 
            new ModelData("East SA Female", "a_f_m_eastsa_01"), new ModelData("East SA Female 2", "a_f_m_eastsa_02"), new ModelData("East SA Male", "a_m_m_eastsa_01"), 
            new ModelData("East SA Male 2", "a_m_m_eastsa_02"), new ModelData("East SA Young Female", "a_f_y_eastsa_01"), new ModelData("East SA Young Female 2", "a_f_y_eastsa_02"), 
            new ModelData("East SA Young Female 3", "a_f_y_eastsa_03"), new ModelData("East SA Young Male", "a_m_y_eastsa_01"), new ModelData("East SA Young Male 2", "a_m_y_eastsa_02"), 
            new ModelData("Ed Toh", "u_m_m_edtoh"), new ModelData("Epsilon Female", "a_f_y_epsilon_01"), new ModelData("Epsilon Male", "a_m_y_epsilon_01"), 
            new ModelData("Epsilon Male 2", "a_m_y_epsilon_02"), new ModelData("Epsilon Tom (CS)", "cs_tomepsilon"), new ModelData("Epsilon Tom (IG)", "ig_tomepsilon"),
            new ModelData("Ex-Army Male", "mp_m_exarmy_01"), new ModelData("Ex-Mil Bum", "u_m_y_militarybum"), new ModelData("Fabien (CS)", "cs_fabien"), new ModelData("Fabien (IG)", "ig_fabien"), 
            new ModelData("Factory Worker Female", "s_f_y_factory_01"), new ModelData("Factory Worker Male", "s_m_y_factory_01"), new ModelData("Families CA Male", "g_m_y_famca_01"), 
            new ModelData("Families DD Male", "mp_m_famdd_01"), new ModelData("Families DNF Male", "g_m_y_famdnf_01"), new ModelData("Families Female", "g_f_y_families_01"), 
            new ModelData("Families FOR Male", "g_m_y_famfor_01"), new ModelData("Families Gang Member?", "csb_ramp_gang"), new ModelData("Families Gang Member? (IG)", "ig_ramp_gang"), 
            new ModelData("Farmer", "a_m_m_farmer_01"), new ModelData("Fat Black Female", "a_f_m_fatbla_01"), new ModelData("Fat Cult Female", "a_f_m_fatcult_01"), 
            new ModelData("Fat Latino Male", "a_m_m_fatlatin_01"), new ModelData("Fat White Female", "a_f_m_fatwhite_01"), new ModelData("Female Agent", "a_f_y_femaleagent"), 
            new ModelData("Ferdinand Kerimov (Mr. K) (CS)", "cs_mrk"), new ModelData("Ferdinand Kerimov (Mr. K) (IG)", "ig_mrk"), new ModelData("FIB Architect", "u_m_m_fibarchitect"), 
            new ModelData("FIB Mugger", "u_m_y_fibmugger_01"), new ModelData("FIB Office Worker", "s_m_m_fiboffice_01"), new ModelData("FIB Office Worker 2", "s_m_m_fiboffice_02"), 
            new ModelData("FIB Security", "mp_m_fibsec_01"), new ModelData("FIB Security", "s_m_m_fibsec_01"), new ModelData("FIB Suit (CS)", "cs_fbisuit_01"), 
            new ModelData("FIB Suit (IG)", "ig_fbisuit_01"), new ModelData("Financial Guru", "u_m_o_finguru_01"), new ModelData("Fireman Male", "s_m_y_fireman_01"), 
            new ModelData("Fitness Female", "a_f_y_fitness_01"), new ModelData("Fitness Female 2", "a_f_y_fitness_02"), new ModelData("Floyd Hebert (CS)", "cs_floyd"), 
            new ModelData("Floyd Hebert (IG)", "ig_floyd"), new ModelData("FOS Rep?", "csb_fos_rep"), new ModelData("Free Mode Female", "mp_f_freemode_01"), 
            new ModelData("Free Mode Male", "mp_m_freemode_01"), new ModelData("Gaffer", "s_m_m_gaffer_01"), new ModelData("Garbage Worker", "s_m_y_garbage"), 
            new ModelData("Gardener", "s_m_m_gardener_01"), new ModelData("Gay Male", "a_m_y_gay_01"), new ModelData("Gay Male 2", "a_m_y_gay_02"), new ModelData("General Fat Male", "a_m_m_genfat_01"), 
            new ModelData("General Fat Male 2", "a_m_m_genfat_02"), new ModelData("General Hot Young Female", "a_f_y_genhot_01"), new ModelData("General Street Old Female", "a_f_o_genstreet_01"), 
            new ModelData("General Street Old Male", "a_m_o_genstreet_01"), new ModelData("General Street Young Male", "a_m_y_genstreet_01"), 
            new ModelData("General Street Young Male 2", "a_m_y_genstreet_02"), new ModelData("Gerald", "csb_g"), new ModelData("GLENSTANK? Male", "u_m_m_glenstank_01"), 
            new ModelData("Golfer Male", "a_m_m_golfer_01"), new ModelData("Golfer Young Female", "a_f_y_golfer_01"), new ModelData("Golfer Young Male", "a_m_y_golfer_01"), 
            new ModelData("Griff", "u_m_m_griff_01"), new ModelData("Grip", "s_m_y_grip_01"), new ModelData("Groom", "csb_groom"), new ModelData("Groom (IG)", "ig_groom"), 
            new ModelData("Grove Street Dealer", "csb_grove_str_dlr"), new ModelData("Guadalope (CS)", "cs_guadalope"), new ModelData("Guido", "u_m_y_guido_01"), 
            new ModelData("Gun Vendor", "u_m_y_gunvend_01"), new ModelData("GURK? (CS)", "cs_gurk"), new ModelData("Hairdresser Male", "s_m_m_hairdress_01"), 
            new ModelData("Hao", "csb_hao"), new ModelData("Hao (IG)", "ig_hao"), new ModelData("Hasidic Jew Male", "a_m_m_hasjew_01"), new ModelData("Hasidic Jew Young Male", "a_m_y_hasjew_01"), 
            new ModelData("Hick", "csb_ramp_hic"), new ModelData("Hick (IG)", "ig_ramp_hic"), new ModelData("High Security", "s_m_m_highsec_01"), new ModelData("High Security 2", "s_m_m_highsec_02"), 
            new ModelData("Highway Cop", "s_m_y_hwaycop_01"), new ModelData("Hiker Female", "a_f_y_hiker_01"), new ModelData("Hiker Male", "a_m_y_hiker_01"), 
            new ModelData("Hillbilly Male", "a_m_m_hillbilly_01"), new ModelData("Hillbilly Male 2", "a_m_m_hillbilly_02"), new ModelData("Hippie Female", "a_f_y_hippie_01"), 
            new ModelData("Hippie Male", "u_m_y_hippie_01"), new ModelData("Hippie Male", "a_m_y_hippy_01"), new ModelData("Hipster", "csb_ramp_hipster"), 
            new ModelData("Hipster (IG)", "ig_ramp_hipster"), new ModelData("Hipster Female", "a_f_y_hipster_01"), new ModelData("Hipster Female 2", "a_f_y_hipster_02"), 
            new ModelData("Hipster Female 3", "a_f_y_hipster_03"), new ModelData("Hipster Female 4", "a_f_y_hipster_04"), new ModelData("Hipster Male", "a_m_y_hipster_01"), 
            new ModelData("Hipster Male 2", "a_m_y_hipster_02"), new ModelData("Hipster Male 3", "a_m_y_hipster_03"), new ModelData("Hooker", "s_f_y_hooker_01"), 
            new ModelData("Hooker 2", "s_f_y_hooker_02"), new ModelData("Hooker 3", "s_f_y_hooker_03"), new ModelData("Hospital Scrubs Female", "s_f_y_scrubs_01"), 
            new ModelData("Hot Posh Female", "u_f_y_hotposh_01"), new ModelData("Hugh Welsh", "csb_hugh"), new ModelData("Hunter (CS)", "cs_hunter"), new ModelData("Hunter (IG)", "ig_hunter"), 
            new ModelData("IAA Security", "s_m_m_ciasec_01"), new ModelData("Impotent Rage", "u_m_y_imporage"), new ModelData("Imran Shinowa", "csb_imran"), new ModelData("Indian Male", "a_m_m_indian_01"), 
            new ModelData("Indian Old Female", "a_f_o_indian_01"), new ModelData("Indian Young Female", "a_f_y_indian_01"), new ModelData("Indian Young Male", "a_m_y_indian_01"), 
            new ModelData("Jane", "u_f_y_comjane"), new ModelData("Janet (CS)", "cs_janet"), new ModelData("Janet (IG)", "ig_janet"), new ModelData("Janitor", "csb_janitor"), 
            new ModelData("Janitor", "s_m_m_janitor"), new ModelData("Jay Norris (IG)", "ig_jay_norris"), new ModelData("Jesco White (Tapdancing Hillbilly)", "u_m_o_taphillbilly"), 
            new ModelData("Jesus", "u_m_m_jesus_01"), new ModelData("Jetskier", "a_m_y_jetski_01"), new ModelData("Jewel Heist Driver", "hc_driver"), new ModelData("Jewel Heist Gunman", "hc_gunman"), 
            new ModelData("Jewel Heist Hacker", "hc_hacker"), new ModelData("Jewel Thief", "u_m_m_jewelthief"), new ModelData("Jeweller Assistant", "u_f_y_jewelass_01"), 
            new ModelData("Jeweller Assistant (CS)", "cs_jewelass"), new ModelData("Jeweller Assistant (IG)", "ig_jewelass"), new ModelData("Jeweller Security", "u_m_m_jewelsec_01"), 
            new ModelData("Jimmy Boston (CS)", "cs_jimmyboston"), new ModelData("Jimmy Boston (IG)", "ig_jimmyboston"), new ModelData("Jimmy De Santa (CS)", "cs_jimmydisanto"), 
            new ModelData("Jimmy De Santa (IG)", "ig_jimmydisanto"), new ModelData("Jogger Female", "a_f_y_runner_01"), new ModelData("Jogger Male", "a_m_y_runner_01"), 
            new ModelData("Jogger Male 2", "a_m_y_runner_02"), new ModelData("John Marston", "mp_m_marston_01"), new ModelData("Johnny Klebitz (CS)", "cs_johnnyklebitz"), 
            new ModelData("Johnny Klebitz (IG)", "ig_johnnyklebitz"), new ModelData("Josef (CS)", "cs_josef"), new ModelData("Josef (IG)", "ig_josef"), new ModelData("Josh (CS)", "cs_josh"), 
            new ModelData("Josh (IG)", "ig_josh"), new ModelData("Juggalo Female", "a_f_y_juggalo_01"), new ModelData("Juggalo Male", "a_m_y_juggalo_01"), new ModelData("Justin", "u_m_y_justin"), 
            new ModelData("Karen Daniels (CS)", "cs_karen_daniels"), new ModelData("Karen Daniels (IG)", "ig_karen_daniels"), new ModelData("Kerry McIntosh (IG)", "ig_kerrymcintosh"), 
            new ModelData("Kifflom Guy", "u_m_y_baygor"), new ModelData("Korean Boss", "g_m_m_korboss_01"), new ModelData("Korean Female", "a_f_m_ktown_01"), 
            new ModelData("Korean Female 2", "a_f_m_ktown_02"), new ModelData("Korean Lieutenant", "g_m_y_korlieut_01"), new ModelData("Korean Male", "a_m_m_ktown_01"), 
            new ModelData("Korean Old Female", "a_f_o_ktown_01"), new ModelData("Korean Old Male", "a_m_o_ktown_01"), new ModelData("Korean Young Male", "g_m_y_korean_01"), 
            new ModelData("Korean Young Male", "a_m_y_ktown_01"), new ModelData("Korean Young Male 2", "g_m_y_korean_02"), new ModelData("Korean Young Male 2", "a_m_y_ktown_02"), 
            new ModelData("Lamar Davis (CS)", "cs_lamardavis"), new ModelData("Lamar Davis (IG)", "ig_lamardavis"), new ModelData("Latino Handyman Male", "s_m_m_lathandy_01"), 
            new ModelData("Latino Street Male 2", "a_m_m_stlat_02"), new ModelData("Latino Street Young Male", "a_m_y_stlat_01"), new ModelData("Latino Young Male", "a_m_y_latino_01"), 
            new ModelData("Lazlow (CS)", "cs_lazlow"), new ModelData("Lazlow (IG)", "ig_lazlow"), new ModelData("Lester Crest (CS)", "cs_lestercrest"), new ModelData("Lester Crest (IG)", "ig_lestercrest"), 
            new ModelData("Life Invader (CS)", "cs_lifeinvad_01"), new ModelData("Life Invader (IG)", "ig_lifeinvad_01"), new ModelData("Life Invader 2 (IG)", "ig_lifeinvad_02"), 
            new ModelData("Life Invader Male", "s_m_m_lifeinvad_01"), new ModelData("Line Cook", "s_m_m_linecook"), new ModelData("Love Fist Willy", "u_m_m_willyfist"), 
            new ModelData("LS Metro Worker Male", "s_m_m_lsmetro_01"), new ModelData("Magenta (CS)", "cs_magenta"), new ModelData("Magenta (IG)", "ig_magenta"), new ModelData("Maid", "s_f_m_maid_01"), 
            new ModelData("Malibu Male", "a_m_m_malibu_01"), new ModelData("Mani", "u_m_y_mani"), new ModelData("Manuel (CS)", "cs_manuel"), new ModelData("Manuel (IG)", "ig_manuel"), 
            new ModelData("Mariachi", "s_m_m_mariachi_01"), new ModelData("Marine", "csb_ramp_marine"), new ModelData("Marine", "s_m_m_marine_01"), new ModelData("Marine 2", "s_m_m_marine_02"), 
            new ModelData("Marine Young", "s_m_y_marine_01"), new ModelData("Marine Young 2", "s_m_y_marine_02"), new ModelData("Marine Young 3", "s_m_y_marine_03"), 
            new ModelData("Mark Fostenburg", "u_m_m_markfost"), new ModelData("Marnie Allen (CS)", "cs_marnie"), new ModelData("Marnie Allen (IG)", "ig_marnie"), 
            new ModelData("Martin Madrazo (CS)", "cs_martinmadrazo"), new ModelData("Mary-Ann Quinn (CS)", "cs_maryann"), new ModelData("Mary-Ann Quinn (IG)", "ig_maryann"), 
            new ModelData("Maude", "csb_maude"), new ModelData("Maude (IG)", "ig_maude"), new ModelData("Maxim Rashkovsky (CS)", "csb_rashcosvki"), new ModelData("Maxim Rashkovsky (IG)", "ig_rashcosvki"), 
            new ModelData("Mechanic", "s_m_y_xmech_01"), new ModelData("Mechanic 2", "s_m_y_xmech_02"), new ModelData("Merryweather Merc", "csb_mweather"), new ModelData("Meth Addict", "a_m_y_methhead_01"), 
            new ModelData("Mexican", "csb_ramp_mex"), new ModelData("Mexican (IG)", "ig_ramp_mex"), new ModelData("Mexican Boss", "g_m_m_mexboss_01"), new ModelData("Mexican Boss 2", "g_m_m_mexboss_02"), 
            new ModelData("Mexican Gang Member", "g_m_y_mexgang_01"), new ModelData("Mexican Goon", "g_m_y_mexgoon_01"), new ModelData("Mexican Goon 2", "g_m_y_mexgoon_02"), 
            new ModelData("Mexican Goon 3", "g_m_y_mexgoon_03"), new ModelData("Mexican Labourer", "a_m_m_mexlabor_01"), new ModelData("Mexican Rural", "a_m_m_mexcntry_01"), 
            new ModelData("Mexican Thug", "a_m_y_mexthug_01"), new ModelData("Michelle (CS)", "cs_michelle"), new ModelData("Michelle (IG)", "ig_michelle"), 
            new ModelData("Migrant Female", "s_f_y_migrant_01"), new ModelData("Migrant Male", "s_m_m_migrant_01"), new ModelData("Milton McIlroy (CS)", "cs_milton"), 
            new ModelData("Milton McIlroy (IG)", "ig_milton"), new ModelData("Mime Artist", "s_m_y_mime"), new ModelData("Minuteman Joe (CS)", "cs_joeminuteman"), 
            new ModelData("Minuteman Joe (IG)", "ig_joeminuteman"), new ModelData("Miranda", "u_f_m_miranda"), new ModelData("Mistress", "u_f_y_mistress"), new ModelData("Misty", "mp_f_misty_01"), 
            new ModelData("Molly (CS)", "cs_molly"), new ModelData("Molly (IG)", "ig_molly"), new ModelData("Money Man (CS)", "csb_money"), new ModelData("Money Man (IG)", "ig_money"), 
            new ModelData("Motocross Biker", "a_m_y_motox_01"), new ModelData("Motocross Biker 2", "a_m_y_motox_02"), new ModelData("Movie Astronaut", "s_m_m_movspace_01"), 
            new ModelData("Movie Director", "u_m_m_filmdirector"), new ModelData("Movie Premiere Female", "s_f_y_movprem_01"), new ModelData("Movie Premiere Female (CS)", "cs_movpremf_01"), 
            new ModelData("Movie Premiere Male", "s_m_m_movprem_01"), new ModelData("Movie Premiere Male (CS)", "cs_movpremmale"), new ModelData("Movie Star Female", "u_f_o_moviestar"), 
            new ModelData("Mrs. Phillips (CS)", "cs_mrsphillips"), new ModelData("Mrs. Phillips (IG)", "ig_mrsphillips"), new ModelData("Mrs. Thornhill (CS)", "cs_mrs_thornhill"), 
            new ModelData("Mrs. Thornhill (IG)", "ig_mrs_thornhill"), new ModelData("Natalia (CS)", "cs_natalia"), new ModelData("Natalia (IG)", "ig_natalia"), 
            new ModelData("Nervous Ron (CS)", "cs_nervousron"), new ModelData("Nervous Ron (IG)", "ig_nervousron"), new ModelData("Nigel (CS)", "cs_nigel"), new ModelData("Nigel (IG)", "ig_nigel"), 
            new ModelData("Niko Bellic", "mp_m_niko_01"), new ModelData("OG Boss", "a_m_m_og_boss_01"), new ModelData("Old Man 1 (CS)", "cs_old_man1a"), new ModelData("Old Man 1 (IG)", "ig_old_man1a"), 
            new ModelData("Old Man 2 (CS)", "cs_old_man2"), new ModelData("Old Man 2 (IG)", "ig_old_man2"), new ModelData("Omega (CS)", "cs_omega"), new ModelData("Omega (IG)", "ig_omega"), 
            new ModelData("O'Neil Brothers (IG)", "ig_oneil"), new ModelData("Ortega", "csb_ortega"), new ModelData("Ortega (IG)", "ig_ortega"), new ModelData("Oscar", "csb_oscar"), 
            new ModelData("Paige Harris (CS)", "csb_paige"), new ModelData("Paige Harris (IG)", "ig_paige"), new ModelData("Paparazzi Male", "a_m_m_paparazzi_01"), 
            new ModelData("Paparazzi Young Male", "u_m_y_paparazzi"), new ModelData("Paramedic", "s_m_m_paramedic_01"), new ModelData("Party Target", "u_m_m_partytarget"), 
            new ModelData("Partygoer", "u_m_y_party_01"), new ModelData("Patricia (CS)", "cs_patricia"), new ModelData("Patricia (IG)", "ig_patricia"), new ModelData("Pest Control", "s_m_y_pestcont_01"),
            new ModelData("Peter Dreyfuss (CS)", "cs_dreyfuss"), new ModelData("Peter Dreyfuss (IG)", "ig_dreyfuss"), new ModelData("Pilot", "s_m_m_pilot_01"), new ModelData("Pilot", "s_m_y_pilot_01"), 
            new ModelData("Pilot 2", "s_m_m_pilot_02"), new ModelData("Pogo the Monkey", "u_m_y_pogo_01"), new ModelData("Polynesian", "a_m_m_polynesian_01"), 
            new ModelData("Polynesian Goon", "g_m_y_pologoon_01"), new ModelData("Polynesian Goon 2", "g_m_y_pologoon_02"), new ModelData("Polynesian Young", "a_m_y_polynesian_01"), 
            new ModelData("Poppy Mitchell", "u_f_y_poppymich"), new ModelData("Porn Dude", "csb_porndudes"), new ModelData("Postal Worker Male", "s_m_m_postal_01"), 
            new ModelData("Postal Worker Male 2", "s_m_m_postal_02"), new ModelData("Priest (CS)", "cs_priest"), new ModelData("Priest (IG)", "ig_priest"), new ModelData("Princess", "u_f_y_princess"), 
            new ModelData("Prison Guard", "s_m_m_prisguard_01"), new ModelData("Prisoner", "s_m_y_prisoner_01"), new ModelData("Prisoner", "u_m_y_prisoner_01"), 
            new ModelData("Prisoner (Muscular)", "s_m_y_prismuscl_01"), new ModelData("Prologue Driver", "u_m_y_proldriver_01"), new ModelData("Prologue Driver", "csb_prologuedriver"), 
            new ModelData("Prologue Host Female", "a_f_m_prolhost_01"), new ModelData("Prologue Host Male", "a_m_m_prolhost_01"), new ModelData("Prologue Host Old Female", "u_f_o_prolhost_01"), 
            new ModelData("Prologue Mourner Female", "u_f_m_promourn_01"), new ModelData("Prologue Mourner Male", "u_m_m_promourn_01"), new ModelData("Prologue Security", "csb_prolsec"), 
            new ModelData("Prologue Security", "u_m_m_prolsec_01"), new ModelData("Prologue Security 2 (CS)", "cs_prolsec_02"), new ModelData("Prologue Security 2 (IG)", "ig_prolsec_02"), 
            new ModelData("PROS?", "mp_g_m_pros_01"), new ModelData("Ranger Female", "s_f_y_ranger_01"), new ModelData("Ranger Male", "s_m_y_ranger_01"), new ModelData("Reporter", "csb_reporter"), 
            new ModelData("Republican Space Ranger", "u_m_y_rsranger_01"), new ModelData("Rival Paparazzo", "u_m_m_rivalpap"), new ModelData("Road Cyclist", "a_m_y_roadcyc_01"), 
            new ModelData("Robber", "s_m_y_robber_01"), new ModelData("Rocco Pelosi", "csb_roccopelosi"), new ModelData("Rocco Pelosi (IG)", "ig_roccopelosi"),
            new ModelData("Rural Meth Addict Female", "a_f_y_rurmeth_01"), new ModelData("Rural Meth Addict Male", "a_m_m_rurmeth_01"), new ModelData("Russian Drunk (CS)", "cs_russiandrunk"), 
            new ModelData("Russian Drunk (IG)", "ig_russiandrunk"), new ModelData("Sales Assistant (High-End)", "s_f_m_shop_high"), new ModelData("Sales Assistant (Low-End)", "s_f_y_shop_low"), 
            new ModelData("Sales Assistant (Mask Stall)", "s_m_y_shop_mask"), new ModelData("Sales Assistant (Mid-Price)", "s_f_y_shop_mid"), new ModelData("Salton Female", "a_f_m_salton_01"), 
            new ModelData("Salton Male", "a_m_m_salton_01"), new ModelData("Salton Male 2", "a_m_m_salton_02"), new ModelData("Salton Male 3", "a_m_m_salton_03"), 
            new ModelData("Salton Male 4", "a_m_m_salton_04"), new ModelData("Salton Old Female", "a_f_o_salton_01"), new ModelData("Salton Old Male", "a_m_o_salton_01"), 
            new ModelData("Salton Young Male", "a_m_y_salton_01"), new ModelData("Salvadoran Boss", "g_m_y_salvaboss_01"), new ModelData("Salvadoran Goon", "g_m_y_salvagoon_01"), 
            new ModelData("Salvadoran Goon 2", "g_m_y_salvagoon_02"), new ModelData("Salvadoran Goon 3", "g_m_y_salvagoon_03"), new ModelData("Scientist", "s_m_m_scientist_01"), 
            new ModelData("Screenwriter", "csb_screen_writer"), new ModelData("Screenwriter (IG)", "ig_screen_writer"), new ModelData("Security Guard", "s_m_m_security_01"), 
            new ModelData("Sheriff Female", "s_f_y_sheriff_01"), new ModelData("Sheriff Male", "s_m_y_sheriff_01"), new ModelData("Shopkeeper", "mp_m_shopkeep_01"), 
            new ModelData("Simeon Yetarian (CS)", "cs_siemonyetarian"), new ModelData("Simeon Yetarian (IG)", "ig_siemonyetarian"), new ModelData("Skater Female", "a_f_y_skater_01"), 
            new ModelData("Skater Male", "a_m_m_skater_01"), new ModelData("Skater Young Male", "a_m_y_skater_01"), new ModelData("Skater Young Male 2", "a_m_y_skater_02"),
            new ModelData("Skid Row Female", "a_f_m_skidrow_01"), new ModelData("Skid Row Male", "a_m_m_skidrow_01"), new ModelData("Snow Cop Male", "s_m_m_snowcop_01"), 
            new ModelData("Solomon Richards (CS)", "cs_solomon"), new ModelData("Solomon Richards (IG)", "ig_solomon"), new ModelData("South Central Female", "a_f_m_soucent_01"), 
            new ModelData("South Central Female 2", "a_f_m_soucent_02"), new ModelData("South Central Latino Male", "a_m_m_socenlat_01"), new ModelData("South Central Male", "a_m_m_soucent_01"), 
            new ModelData("South Central Male 2", "a_m_m_soucent_02"), new ModelData("South Central Male 3", "a_m_m_soucent_03"), new ModelData("South Central Male 4", "a_m_m_soucent_04"), 
            new ModelData("South Central MC Female", "a_f_m_soucentmc_01"), new ModelData("South Central Old Female", "a_f_o_soucent_01"), new ModelData("South Central Old Female 2", "a_f_o_soucent_02"), 
            new ModelData("South Central Old Male", "a_m_o_soucent_01"), new ModelData("South Central Old Male 2", "a_m_o_soucent_02"), new ModelData("South Central Old Male 3", "a_m_o_soucent_03"), 
            new ModelData("South Central Young Female", "a_f_y_soucent_01"), new ModelData("South Central Young Female 2", "a_f_y_soucent_02"), new ModelData("South Central Young Female 3", "a_f_y_soucent_03"), 
            new ModelData("South Central Young Male", "a_m_y_soucent_01"), new ModelData("South Central Young Male 2", "a_m_y_soucent_02"), new ModelData("South Central Young Male 3", "a_m_y_soucent_03"), 
            new ModelData("South Central Young Male 4", "a_m_y_soucent_04"), new ModelData("Sports Biker", "u_m_y_sbike"), new ModelData("Spy Actor", "u_m_m_spyactor"), 
            new ModelData("Spy Actress", "u_f_y_spyactress"), new ModelData("Stag Party Groom", "u_m_y_staggrm_01"), new ModelData("Steve Haines (CS)", "cs_stevehains"), 
            new ModelData("Steve Haines (IG)", "ig_stevehains"), new ModelData("Street Performer", "s_m_m_strperf_01"), new ModelData("Street Preacher", "s_m_m_strpreach_01"), 
            new ModelData("Street Punk", "g_m_y_strpunk_01"), new ModelData("Street Punk 2", "g_m_y_strpunk_02"), new ModelData("Street Vendor", "s_m_m_strvend_01"), 
            new ModelData("Street Vendor Young", "s_m_y_strvend_01"), new ModelData("Stretch (CS)", "cs_stretch"), new ModelData("Stretch (IG)", "ig_stretch"), new ModelData("Stripper", "csb_stripper_01"), 
            new ModelData("Stripper", "s_f_y_stripper_01"), new ModelData("Stripper 2", "csb_stripper_02"), new ModelData("Stripper 2", "s_f_y_stripper_02"), new ModelData("Stripper Lite", "s_f_y_stripperlite"), 
            new ModelData("Stripper Lite", "mp_f_stripperlite"), new ModelData("Sunbather Male", "a_m_y_sunbathe_01"), new ModelData("Surfer", "a_m_y_surfer_01"), new ModelData("SWAT", "s_m_y_swat_01"), 
            new ModelData("Sweatshop Worker", "s_f_m_sweatshop_01"), new ModelData("Sweatshop Worker Young", "s_f_y_sweatshop_01"), new ModelData("Talina (IG)", "ig_talina"), 
            new ModelData("Tanisha (CS)", "cs_tanisha"), new ModelData("Tanisha (IG)", "ig_tanisha"), new ModelData("Tao Cheng (CS)", "cs_taocheng"), new ModelData("Tao Cheng (IG)", "ig_taocheng"), 
            new ModelData("Tao's Translator (CS)", "cs_taostranslator"), new ModelData("Tao's Translator (IG)", "ig_taostranslator"), new ModelData("Tattoo Artist", "u_m_y_tattoo_01"), 
            new ModelData("Tennis Coach (CS)", "cs_tenniscoach"), new ModelData("Tennis Coach (IG)", "ig_tenniscoach"), new ModelData("Tennis Player Female", "a_f_y_tennis_01"), 
            new ModelData("Tennis Player Male", "a_m_m_tennis_01"), new ModelData("Terry (CS)", "cs_terry"), new ModelData("Terry (IG)", "ig_terry"), new ModelData("The Lost MC Female", "g_f_y_lost_01"), 
            new ModelData("The Lost MC Male", "g_m_y_lost_01"), new ModelData("The Lost MC Male 2", "g_m_y_lost_02"), new ModelData("The Lost MC Male 3", "g_m_y_lost_03"), 
            new ModelData("Tom (CS)", "cs_tom"), new ModelData("Tonya", "csb_tonya"), new ModelData("Tonya (IG)", "ig_tonya"), new ModelData("Topless", "a_f_y_topless_01"), 
            new ModelData("Tourist Female", "a_f_m_tourist_01"), new ModelData("Tourist Male", "a_m_m_tourist_01"), new ModelData("Tourist Young Female", "a_f_y_tourist_01"), 
            new ModelData("Tourist Young Female 2", "a_f_y_tourist_02"), new ModelData("Tracey De Santa (CS)", "cs_tracydisanto"), new ModelData("Tracey De Santa (IG)", "ig_tracydisanto"),
            new ModelData("Traffic Warden", "csb_trafficwarden"), new ModelData("Traffic Warden (IG)", "ig_trafficwarden"), new ModelData("Tramp Female", "a_f_m_tramp_01"), 
            new ModelData("Tramp Male", "a_m_m_tramp_01"), new ModelData("Tramp Old Male", "u_m_o_tramp_01"), new ModelData("Tramp Old Male", "a_m_o_tramp_01"), 
            new ModelData("Transport Worker Male", "s_m_m_gentransport"), new ModelData("Transvestite Male", "a_m_m_tranvest_01"), new ModelData("Transvestite Male 2", "a_m_m_tranvest_02"), 
            new ModelData("Trucker Male", "s_m_m_trucker_01"), new ModelData("Tyler Dixon (IG)", "ig_tylerdix"), new ModelData("Undercover Cop", "csb_undercover"), 
            new ModelData("United Paper Man (CS)", "cs_paper"), new ModelData("United Paper Man (IG)", "ig_paper"), new ModelData("UPS Driver", "s_m_m_ups_01"), new ModelData("UPS Driver 2", "s_m_m_ups_02"), 
            new ModelData("US Coastguard", "s_m_y_uscg_01"), new ModelData("Vagos Female", "g_f_y_vagos_01"), new ModelData("Valet", "s_m_y_valet_01"), 
            new ModelData("Vespucci Beach Male", "a_m_y_beachvesp_01"), new ModelData("Vespucci Beach Male 2", "a_m_y_beachvesp_02"), new ModelData("Vinewood Douche", "a_m_y_vindouche_01"), 
            new ModelData("Vinewood Female", "a_f_y_vinewood_01"), new ModelData("Vinewood Female 2", "a_f_y_vinewood_02"), new ModelData("Vinewood Female 3", "a_f_y_vinewood_03"), 
            new ModelData("Vinewood Female 4", "a_f_y_vinewood_04"), new ModelData("Vinewood Male", "a_m_y_vinewood_01"), new ModelData("Vinewood Male 2", "a_m_y_vinewood_02"), 
            new ModelData("Vinewood Male 3", "a_m_y_vinewood_03"), new ModelData("Vinewood Male 4", "a_m_y_vinewood_04"), new ModelData("Wade (CS)", "cs_wade"), new ModelData("Wade (IG)", "ig_wade"), 
            new ModelData("Waiter", "s_m_y_waiter_01"), new ModelData("Wei Cheng (CS)", "cs_chengsr"), new ModelData("Wei Cheng (IG)", "ig_chengsr"), new ModelData("White Street Male", "a_m_y_stwhi_01"), 
            new ModelData("White Street Male 2", "a_m_y_stwhi_02"), new ModelData("Window Cleaner", "s_m_y_winclean_01"), new ModelData("Yoga Female", "a_f_y_yoga_01"), 
            new ModelData("Yoga Male", "a_m_y_yoga_01"), new ModelData("Zimbor (CS)", "cs_zimbor"), new ModelData("Zimbor (IG)", "ig_zimbor"), new ModelData("Zombie", "u_m_y_zombie_01")
        };
    }
}
